spring:
  application:
    name: Backend

  servlet:
    multipart:
      max-file-size: "50MB"
      max-request-size: "65MB"

  mongodb:
    uri: "mongodb+srv://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@cluster0.96svcb8.mongodb.net/?appName=Cluster0"
    database: "test"

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

app:
  static:
    dir: "./static/"
  jwt:
    access-secret: ${JWT_ACCESS_SECRET}
    refresh-secret: ${JWT_REFRESH_SECRET}
    access-expiration-ms: 900000
    refresh-expiration-ms: 604800000

aws:
  accessKey: "${AWS_ACCESS_KEY_ID}"
  secretKey: "${AWS_SECRET_ACCESS_KEY}"
  region: "ap-southeast-2"
  bucketName: "fckedu-backend-storage-static"