import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { dehydrate, QueryClient, HydrationBoundary } from "@tanstack/react-query";
import { headers } from "next/headers";
import { getMeService } from "@/presentation/services/user.service";
import QueryProvider from "@/provider/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Generate Exam",
  description: "Generated by Doan Nhu Son",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  const headersList = await headers();

  const hasAccountId = headersList.get("x-account-id");

  if (hasAccountId) {
    try {
      await queryClient.prefetchQuery({
        queryKey: ["user-profile"],
        queryFn: async () => getMeService(),
      });
    } catch (error) {
      console.error("Lỗi prefetch profile từ Spring Boot:", error);
    }
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <HydrationBoundary state={dehydrate(queryClient)}>
            {children}
          </HydrationBoundary>
        </QueryProvider>
      </body>
    </html>
  );
}
